### PR TITLE
align API names with Constraint

### PR DESCRIPTION
**Pull request by mmoskal**

### CODE REVIEW

**Review by hudson-ai — APPROVED** [review]
LGTM

**Comment by hudson-ai** [comment]
@mmoskal is `commit_token` returning None on the last call the only real semantic change here beyond renaming the methods?

**Comment by hudson-ai** [comment]
@lochuynh1412 pinging you for visibility

**Comment by mmoskal** [comment]
I reverted the `commit_token()` change, since it was returning stop only in case `compute_mask()` already did (in which case we don't even call it); easier to keep it as it was

**Pull request merged**
